// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: "AIzaSyB6bvYq5N0LLcKhr-2-fYXr1G9DbW5rkAA",
    authDomain: "pms1-89339.firebaseapp.com",
    projectId: "pms1-89339",
    storageBucket: "pms1-89339.firebasestorage.app",
    messagingSenderId: "48107780541",
    appId: "1:48107780541:web:07e48a4c3bfaf9f60c7ad4",
    measurementId: "G-ZWMM4JFXZK",
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: "AIzaSyB6bvYq5N0LLcKhr-2-fYXr1G9DbW5rkAA",
    appId: "1:48107780541:android:07e48a4c3bfaf9f60c7ad4",
    messagingSenderId: "48107780541",
    projectId: "pms1-89339",
    storageBucket: "pms1-89339.firebasestorage.app",
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: "AIzaSyB6bvYq5N0LLcKhr-2-fYXr1G9DbW5rkAA",
    appId: "1:48107780541:ios:07e48a4c3bfaf9f60c7ad4",
    messagingSenderId: "48107780541",
    projectId: "pms1-89339",
    storageBucket: "pms1-89339.firebasestorage.app",
    iosClientId: "48107780541-abcdefghijklmnop.apps.googleusercontent.com",
    iosBundleId: 'com.example.pms',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: "AIzaSyB6bvYq5N0LLcKhr-2-fYXr1G9DbW5rkAA",
    appId: "1:48107780541:macos:07e48a4c3bfaf9f60c7ad4",
    messagingSenderId: "48107780541",
    projectId: "pms1-89339",
    storageBucket: "pms1-89339.firebasestorage.app",
    iosClientId: "48107780541-abcdefghijklmnop.apps.googleusercontent.com",
    iosBundleId: 'com.example.pms',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: "AIzaSyB6bvYq5N0LLcKhr-2-fYXr1G9DbW5rkAA",
    appId: "1:48107780541:windows:07e48a4c3bfaf9f60c7ad4",
    messagingSenderId: "48107780541",
    projectId: "pms1-89339",
    storageBucket: "pms1-89339.firebasestorage.app",
  );
}
